### ISSUE TITLE
Allow for specifying Domain Display Name for password based authentication

### ISSUE THREAD

**Issue by surendarchandra** [rubrikinc/rubrik-sdk-for-python#104]
**Is your feature request related to a problem? Please describe.**

In Rubrik CDM 5.0, if the Domain Display Name is not specified, then the Rubrik CDM will
first try the local domain before iterating through all the configured LDAP domains.
This can be slow and create many false alarms.

**Describe the solution you'd like**

An option to Connect() to specify the Domain Display Name.

**Describe alternatives you've considered**

There is no other way to specify an additional parameter using BASIC auth.

**Additional context**

Specifying Domain Display Name will generate an API token. This should also speed
up further API interactions, especially when using LDAP domain.

**Comment by rfitzhugh** [comment]
Hi @surendarchandra , does PR #112 solve this issue? If so, I'll close it.

**Comment by surendarchandra** [comment]
We had to revert that fix. Working on another way. @rfitzhugh

**Comment by drew-russell** [comment]
@surendarchandra @rfitzhugh any updates on this one?

**Comment by drew-russell** [comment]
@surendarchandra going to close this one out. Let me know if you want to reopen.
