### ISSUE TITLE
Get SQL database live mounts

### ISSUE THREAD

**Issue by promiseowolabi** [rubrikinc/rubrik-sdk-for-python#138]
**Is your feature request related to a problem? Please describe.**

The only way to retrieve database live mounts is through the API or CDM. Developers will benefit from a python function to query the sql mount api based on instance name, hostname, clone name etc.

**Describe the solution you'd like**

Implement a function in data_management.py i.e. `get_sql_live_mount`

**Comment by rfitzhugh** [comment]
Does the referenced PR close this issue?

**Comment by promiseowolabi** [comment]
Yes it does, I'll close the issue. Thanks.
