### ISSUE TITLE
Validate SQL db based on the db_name, sql_instance, sql_host

### ISSUE THREAD

**Issue by promiseowolabi** [rubrikinc/rubrik-sdk-for-python#139]
**Is your feature request related to a problem? Please describe.**

In order to retrieve a database ID the user provides a database name, sql instance and sql host. It will be assumed that the combination of **ALL** three values will provide a unique database within CDM.
This function will be used in:
`sql_live_mount`
`sql_live_unmount`
`get_sql_live_mount`

**Describe the solution you'd like**

This operation will be repeated in many data_management.py MSSQL related functions, hence I'm writing a specific internal function `_validate_sql_db` for this.

**Comment by rfitzhugh** [comment]
Does the referenced PR close this issue?

**Comment by promiseowolabi** [comment]
Yes it does, thanks.
