### ISSUE TITLE
Auto-generate documentation

### ISSUE THREAD

**Issue by drew-russell** [rubrikinc/rubrik-sdk-for-python#170]
We need to add a unit test that validates all functions have a corresponding doc .md file and an entry in the `/docs/SUMMARY.md`

**Comment by rzferchichi** [comment]
This doesn't belong in the unit test suit, rather use a linter or create a script that can be added to the CI pipeline to verify that this is the case.

**Comment by drew-russell** [comment]
Let's change this to updating the `create_docs.py` to be more stable.

**Comment by rfitzhugh** [comment]
Re-open if this was not solved by PR #197
