### ISSUE TITLE
Enable archive consolidation fully

### ISSUE THREAD

**Issue by Jblac03** [rubrikinc/rubrik-sdk-for-python#203]
I am using the module "aws_s3_cloudon"  Enable CloudOn for an exsiting AWS S3 archival location. However although it does set the vpc_id, subnet_id, security_group_id it does not set the "Enable Archive Consolidation" checkbox

I would like to fully have the ability to turn this on and off via the sdk.

Thanks
John

**Comment by drew-russell** [comment]
@Jblac03 I have the necessary updates in place, and I am working through our review process. Once that is finished I will create a new version of the SDK for download that includes the requested update.

**Comment by Jblac03** [comment]
Thanks Drew very much appreciated.

**Comment by drew-russell** [comment]
@Jblac03 v2.0.7 of the SDK is available. 

The `aws_s3_cloudon()` function now has an optional `enable_archive_consolidation` value added. If you set this to true, archive consolidation will be enabled for you.

```
archive_name = "AWS:S3:rubrikpythonsdk"
vpc_id = 'vpc-8d80iii9'
subnet_id = 'subnet-125b5q79'
security_group_id = 'sg-f31bb489'
enable_archive_consolidation = True

cloudon = rubrik.aws_s3_cloudon(archive_name, vpc_id, subnet_id, security_group_id, enable_archive_consolidation)
```

**Comment by Jblac03** [comment]
Hey Drew,

Great turnaround on this.

Thanks
John
