### ISSUE TITLE
Comment needs updating in cloud.py

### ISSUE THREAD

**Issue by DamaniN** [rubrikinc/rubrik-sdk-for-python#204]
**Expected Behavior**

Correct comments in `https://github.com/rubrikinc/rubrik-sdk-for-python/blob/devel/rubrik_cdm/cloud.py`

**Current Behavior**

What is the current behavior?

This comment in https://github.com/rubrikinc/rubrik-sdk-for-python/blob/devel/rubrik_cdm/cloud.py:

```python
    def azure_cloudon(self, archive_name, container, storage_account_name, application_id, application_key, tenant_id, region, virtual_network_id, subnet_name, security_group_id, timeout=30):  # pylint: ignore
        """Enable CloudOn for an exsiting AWS S3 archival location.
```
 
Should be:

```python
    def azure_cloudon(self, archive_name, container, storage_account_name, application_id, application_key, tenant_id, region, virtual_network_id, subnet_name, security_group_id, timeout=30):  # pylint: ignore
        """Enable CloudOn for an existing Azure archival location.
```

Note: The spelling correction and reference to Azure.

**Failure Information (for bugs)**

None

* Use verbose outputs to capture any debug information.

None

**Steps to Reproduce**

Review the code.

**Context**

None

**Failure Logs**

None

* Use verbose outputs to capture any debug information.

None

**Comment by drew-russell** [comment]
Updated in #208
