### ISSUE TITLE
Rename *_cloudon functions to *_cloud_compute

### ISSUE THREAD

**Issue by DamaniN** [rubrikinc/rubrik-sdk-for-python#205]
**Is your feature request related to a problem? Please describe.**

The *_cloudon functions in https://github.com/rubrikinc/rubrik-sdk-for-python/blob/devel/rubrik_cdm/cloud.py should be renamed to *_archival_compute. These include:

`aws_s3_cloudon`
`azure_cloudon`

The reason being that the cloud compute settings that these functions update are used by more than just CloudOn. Archival Consolidation and Smart Tiering now use these settings as well. This change will also facilitate the implementation of updating the archival proxy as well as compute proxy in a later release. 

The new functions should be called:

`aws_archival_compute`
`azure_archival_compute`

**Comment by DamaniN** [comment]
Relates to #206

**Comment by drew-russell** [comment]
Don't want to rename here. Probably best to deprecate and then create a more generic function.

**Comment by shamsway** [comment]
Agree that renaming is problematic. We could use an alias for these functions and eventually deprecate the existing name. Same for https://github.com/rubrikinc/rubrik-sdk-for-python/issues/206.

**Comment by shamsway** [comment]
I have documented this in our roadmap for the Python SDK. I am going to close this issue, but the team that does future SDK development work will be aware of this.
