### ISSUE TITLE
The *_cloudout functions should be renamed to *_archival_location

### ISSUE THREAD

**Issue by DamaniN** [rubrikinc/rubrik-sdk-for-python#206]
**Is your feature request related to a problem? Please describe.**

This request is related to #205.

The *_cloudout functions in https://github.com/rubrikinc/rubrik-sdk-for-python/blob/devel/rubrik_cdm/cloud.py should be renamed to *_archival_location. These include:

`aws_s3_cloudout`
`update_aws_s3_cloudout`
`azure_cloudout`

While these functions are used to configure CloudOut the objects that they actually configure in Rubrik are called Archival Locations. This change will also allow the configuration of on-prem Archival locations for things like S3 object stores, NFS object stores, etc... It will also make the configuration of the Compute Settings (*_archival_compute), Archival Proxy (*_archival_proxy) and Compute Proxy (*_archival_compute_proxy) more consistent. The new functions would be:

`aws_archival_location`
`update_aws_archival_location`
`azure_archival_location`

**Comment by drew-russell** [comment]
Don't want to rename here. Probably best to deprecate and then create a more generic function.

**Comment by shamsway** [comment]
I have documented this in our roadmap for the Python SDK. I am going to close this issue, but the team that does future SDK development work will be aware of this.
