### ISSUE TITLE
Only one object type available for get_sla_object

### ISSUE THREAD

**Issue by hbuter-rubrik** [rubrikinc/rubrik-sdk-for-python#226]
Currently when using get_sla_object you can only define vmware as your object type. 

I like to see other object types to be added such as sql, oracle, windows volumes, file sets etc 

**Describe alternatives you've considered**

just starting out in Python, so not have too much experience is using the get api functionality, assuming you can use this as a workaround

**Comment by drew-russell** [comment]
@hbuter-rubrik The next SDK release will include support for `hyper-v, mssql_db, ec2_instance, oracle_db, vcd, managed_volume, ahv, nas_share, linux_and_unix_host, windows_host`
