### ISSUE TITLE
Increase CloudOut Timeout values

### ISSUE THREAD

**Issue by drew-russell** [rubrikinc/rubrik-sdk-for-python#23]
**What would you like to be added**:

Increase the default timeout value for `aws_s3_clodout` and `azure_cloudout`

**Why is this needed**:

When adding a new archive location it may take longer than default 15 seconds to get a response from AWS/Azure which results in a timeout error message. The default timeout should be increased to a minimum of 3 minutes to account for this.

**Comment by mo6020** [comment]
The default on this looks to be 30 secs?

**Comment by drew-russell** [comment]
Closed via #24
