### ISSUE TITLE
Improve create_sla() error message

### ISSUE THREAD

**Issue by drew-russell** [rubrikinc/rubrik-sdk-for-python#236]
**Is your feature request related to a problem? Please describe.**

The `create_sla()` function will return a "The Rubrik cluster already has an SLA Domain named `name`" error message when Rubrik cluster has an SLA named `name` that has different parameters than those provided.

This error message may not make it 100% clear why the error message is being thrown.

**Describe the solution you'd like**

An improved error message that is more obvious.

**Comment by shamsway** [comment]
Resolved by #237
