### ISSUE TITLE
Add ability to specify a replication target in create_sla()

### ISSUE THREAD

**Issue by KowMangler** [rubrikinc/rubrik-sdk-for-python#249]
**Is your feature request related to a problem? Please describe.**

Can't specify a replication target and replication retention when creating the SLA requires an extra step to complete SLA configuration.

**Describe the solution you'd like**

Add options to specify replication target and replication retention in days

**Describe alternatives you've considered**

Use patch method to update the SLA or just create the SLA using raw api calls.

**Additional context**

**Comment by jaapbrasser** [comment]
Fixed by #251 , thanks @KowMangler !
