### ISSUE TITLE
Add Nutanix AHV cluster refresh functionality

### ISSUE THREAD

**Issue by eramnes** [rubrikinc/rubrik-sdk-for-python#266]
**Is your feature request related to a problem? Please describe.**
We would like to be able to refresh the VMs inside a Nutanix AHV cluster in Rubrik.  This is required when assigning SLAs to newly created VMs, as they don't show up in Rubrik until the scheduled cluster refresh.  We want to be able to trigger the refresh of the cluster from code.

**Describe the solution you'd like**
Add functionality to refresh Nutanix AHV clusters.

**Describe alternatives you've considered**
It is possible to wait for scheduled refreshes, but this slows down an automation process significantly.

**Comment by jaapbrasser** [comment]
Thanks for reporting this issue, this is something we'll look at implementing!

**Comment by jaapbrasser** [comment]
Thanks for contributing @eramnes, I've reviewed and merged your changes!
