### ISSUE TITLE
Support Read Only API token in CDM 5.0

### ISSUE THREAD

**Issue by mtellin** [rubrikinc/rubrik-sdk-for-python#28]
Requesting support for Read Only API token capabilities from CDM 5.0.

**Comment by justinrush** [comment]
This would be super helpful - we have some scripts we wrote the drop data into Influxdb and we'd prefer not to have it use an admin account - using a token is even better than a user/pass.

**Comment by drew-russell** [comment]
Will need to update the following in `rubrik_cdm.py` to support the token:

Add `token` (or similar verbiage) to the `init` and then add additional logic to prevent error from being thrown if only the token is provided (i.e no username / password) 

```python
class Connect(_CLUSTER, _DATA_MANAGEMENT, _PHYSICAL, _CLOUD):
  

    def __init__(self, node_ip=None, username=None, password=None, enable_logging=False):
        

        if node_ip is None:
            node_ip = os.environ.get('rubrik_cdm_node_ip')
            if node_ip is None:
                sys.exit("Error: The Rubrik CDM Node IP has not been provided.")
            else:
                self.node_ip = node_ip
        else:
            self.node_ip = node_ip

        if username is None:
            username = os.environ.get('rubrik_cdm_username')
            if username is None:
                sys.exit("Error: The Rubrik CDM Username has not been provided.")
            else:
                self.username = username
        else:
            self.username = username

        if password is None:
            password = os.environ.get('rubrik_cdm_password')
            if password is None:
                sys.exit("Error: The Rubrik CDM Password has not been provided.")
            else:
                self.password = password
        else:
            self.password = password
```

And then if token is provided the correct authorization header needs to be returned

```python

def _authorization_header(self):
```

**Comment by drew-russell** [comment]
I'm not sure what error message we return when we try to doing something like a `POST` when using the new R/O token but lets make sure it's obvious as well.

**Comment by drew-russell** [comment]
Support added via https://github.com/rubrikinc/rubrik-sdk-for-python/commit/cfc7847b92ffb3190650226249cc0358d1cdbf56

Also created new `create_user()` and `read_only_authorization()` functions for easier management of read-only roles.
