### ISSUE TITLE
Should encode spaces in endpoint with + instead of %20

### ISSUE THREAD

**Issue by ryanmatthews** [rubrikinc/rubrik-sdk-for-python#29]
Currently the request URL is encoded with urllib.quote, which encodes spaces as %20. The browser encodes the same query with a plus instead. There is a function in python which does the same (urllib.quote_plus). The functionality seems the same, but the plus is way more readable.

**Comment by ryanmatthews** [comment]
sample endpoint:

/event?event_type=Audit&after_date=Sunday February 10 2019 12:00:00 am&after_id=2019-02-10:06:2:::1549779907376-d4341d9e-7289-40f0-9e12-b87fb2872c7b

**Comment by geluyan** [comment]
After some research it’s rather a discussion than an issue. Mostly it depends on the application. I prefer to use the current urllib.qoute just for the reason that this will encode the URL & the query part.

For example:
`http://www.example.com/path/foo+bar/path?query+name=query+value`

In this URL, the parameter name is `query name` with a space and the value is `query value` with a space, but the folder name in the path is literally `foo+bar`, not `foo bar`.

If we keep using the `%20`, the path is literally `foo bar`. I know spaces should never be used in URL formatting :-p

**Comment by pmilano1** [comment]
Also keep in mind that urllib caters to other characters that require escaping within URL query parameters.

**Comment by drew-russell** [comment]
Talked to @ryanmatthews about this, we’re going to keep the code as is and re-open in the future if appropriate.
