### ISSUE TITLE
Psuedocode assignment operator in example

### ISSUE THREAD

**Issue by michaelcoyote** [rubrikinc/rubrik-sdk-for-python#30]
Example in docs/quick-start.md uses pseudocode assignment instead of standard python assignment (`:=` vs `=`).

**Expected Behavior**

Assignments as in doc will cause syntax error.

**Current Behavior**

What is the current behavior?

**Failure Information (for bugs)**

Please help provide information about the failure if this is a bug.

* Use verbose outputs to capture any debug information.
```
Paste into a code block.
```

**Steps to Reproduce**

Please provide detailed steps for reproducing the issue.

* Use numbered list.

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version of project.
* Version of dependencies.
* Version of operating system.

**Failure Logs**

Please include any relevant log snippets or files here.

* Use verbose outputs to capture any debug information.

```
Paste into a code block.
```

**Comment by drew-russell** [comment]
Looks like we got our Go and Python mixed up here :)

```
# Set Object Variables
vm_name := "VM1"
sla_name := "Gold"
object_type := "VMware"
```

**Comment by michaelcoyote** [comment]
doing a PR now unless you have one  :)

**Comment by drew-russell** [comment]
I'll keep an eye out for it @michaelcoyote !

**Comment by michaelcoyote** [comment]
@drew-russell I finished it and it's linked to this issue.

**Comment by drew-russell** [comment]
@michaelcoyote can you submit a PR from your fork to our main repo and then I can merge?

**Comment by drew-russell** [comment]
Closed via https://github.com/rubrikinc/rubrik-sdk-for-python/pull/31
