### ISSUE TITLE
On Demand DB Snapshots

### ISSUE THREAD

**Issue by drew-russell** [rubrikinc/rubrik-sdk-for-python#42]
**Describe the solution you'd like**

Add the ability to backup DBs using the `on_demand_snapshot()` function

**Comment by Jhildre** [comment]
I would like to be able to do all DB's on a server

**Comment by shamsway** [comment]
@drew-russell @Draper1 there's a merged PR here, any reason this issue is still open?

**Comment by Jhildre** [comment]
I know I did not get a fix.

Jim Hildreth  SunStream Business Services  Phone: 651-282-8691

**Comment by drew-russell** [comment]
@shamsway Yes, good call. We can close this out.

@Jhildre The code is currently in our `devel` branch and will be included in our next update which we expect soon.

Devel Documentation: https://rubrik.gitbook.io/rubrik-sdk-for-python/v/devel/data-management-functions/on_demand_snapshot
