### ISSUE TITLE
Update Bootstrap for 5.0 API Change

### ISSUE THREAD

**Issue by drew-russell** [rubrikinc/rubrik-sdk-for-python#53]
**Expected Behavior**

NTP Configuration to be successfully applied during the bootstrap of a 5.0 Cluster

**Current Behavior**

The NTP Configuration does not apply.

**Failure Information (for bugs)**

Pre 5.0 `/internal/cluster/{id}/bootstrap` API config

```python
  "ntpServers": [
    "string"
  ],
```

Post 5.0 config

```python
"ntpServerConfigs": [
    {
      "server": "string",
      "symmetricKey": {
        "keyId": 0,
        "key": "string",
        "keyType": "string"
      }
    }
  ],
```

**Comment by ameyanator** [comment]
Hi I am interested to solve this issue. I am a newbie to open source contributions and am trying to figure my way out. Could someone please help me as to where I can find the code to solve this issue. I have forked and cloned the repo but do not understand where to go from here.

**Comment by drew-russell** [comment]
@ameyanator awesome!!

The `setup_cluster()` function in `rubrik_cdm/rubrik_cdm.py` is what controls the bootstrap process. You'll want to make sure you are working off of the `devel` branch, which is where all the latest code is present, as well.

For this issue we need to add a check to determine which version of CDM is running and then based off of that send the correct config. 

```python
if self.minimum_installed_cdm_version(5.0) is True:
    bootstrap_config["ntpServerConfigs"] = [
        {
            "server": ntp_servers
        }
    ]
else:
    bootstrap_config["ntpServers"] = ntp_servers
```

In this case we are using the `minimum_installed_cdm_version()` function to check if CDM version 5.0 is installed or not and then sending the correct configuration based off of that.

This particular code should start on line 272 in `rubrik_cdm.py`.

Once you have the code in place you'll just make a pull request to the main `devel` branch, and we can review it from there. You'll want to make sure you're only updating the `rubrik_cdm.py` file there as well. Please reach out again if need any help on that side as well! It can definitely be confusing the first few times you do it.
