### ISSUE TITLE
return of the VM name after a live mount

### ISSUE THREAD

**Issue by MrP1xel** [rubrikinc/rubrik-sdk-for-python#74]
Hello,
it would be great to be able to easily retrieve the name of the VM created after a snapshot live mount

Or in the rubrik.vsphere_live_mount , to be able to specify a vm name for the VM to be mounted

**Comment by MrP1xel** [comment]
From the return of the API request : `/vmware/vm/snapshot/{id}/mount`

we can catch the ID of the snapshot 

>  "id": "string"

Then invoke the API `/vmware/vm/snapshot/{id}`

and catch the VM name in the response 

>  "virtualMachine": {
> "id": "string",
> "name": "string",

**Comment by promiseowolabi** [comment]
Currently the `'mountedVmId'` doesn't exist when the mount is queued i.e. `'/vmware/vm/snapshot/mount?vm_id={}'` will return `'isReady'=false`

I will submit a pull request for `get_vsphere_live_mount_names` to return a list on mounted vms for a particular vm.

**Comment by shamsway** [comment]
Looks like this is resolved - closing issue.
